table dimHealthySpecies
	lineageTag: 06933410-ab0b-4fea-b4a7-af7aca35c8a7

	column 'Species Present in Area'
		dataType: string
		lineageTag: bf4728fe-6137-4d25-b5dd-0b6700f1373b
		summarizeBy: none
		sourceColumn: Species Present in Area

		annotation SummarizationSetBy = Automatic

	column HealthySpeciesID
		dataType: int64
		formatString: 0
		lineageTag: 23a7a8ab-ab46-42ca-95eb-f067926658ed
		summarizeBy: none
		sourceColumn: HealthySpeciesID

		annotation SummarizationSetBy = Automatic

	partition dimHealthySpecies = m
		mode: import
		queryGroup: 'Healthy Vegetation'
		source =
				let
				    Source = Table.Combine({#"Vegetation Yoho", #"Vegetation Kootenay"}),
				    #"Replaced Value" = Table.ReplaceValue(Source,"","Sonchus arvensis",Replacer.ReplaceValue,{"Species Present in Area"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value", {"Plot Identification"}, dimHealthyPlot, {"Plot Identification"}, "dimHealthyPlot", JoinKind.LeftOuter),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"Species Present in Area"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "HealthySpeciesID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

