table 'Invasive Yoho'
	isHidden
	lineageTag: 48b90ae3-2d38-4254-affe-993e38d77664

	column Park
		dataType: string
		isHidden
		lineageTag: 7fe8c8ec-aa1a-4256-8005-2f928d58dc44
		summarizeBy: none
		sourceColumn: Park

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		isHidden
		lineageTag: 30548eb8-6ba6-4315-8519-7d3f79ee9f34
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Plot
		dataType: string
		isHidden
		lineageTag: f0fe7824-95ab-4809-a9f2-38ecd54a2787
		summarizeBy: none
		sourceColumn: Plot

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Species
		dataType: string
		isHidden
		lineageTag: fcb54083-2c67-4919-93dc-0c9249673646
		summarizeBy: none
		sourceColumn: Species

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: string
		isHidden
		lineageTag: 96114606-0837-457f-84e2-ce2f616183c0
		summarizeBy: none
		sourceColumn: Latitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: string
		isHidden
		lineageTag: 40cd72c1-a086-4ef8-a86a-3a89bccaa2a7
		summarizeBy: none
		sourceColumn: Longitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Province
		dataType: string
		isHidden
		lineageTag: 0612014b-731d-44bf-be6f-7f5acfeb4ea5
		summarizeBy: none
		sourceColumn: Province

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Plot Area (m2)'
		dataType: string
		isHidden
		lineageTag: 776262fb-bc26-445a-9457-97575c04c10b
		summarizeBy: none
		sourceColumn: Plot Area (m2)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of Trees in Plot'
		dataType: string
		isHidden
		lineageTag: ad9c39b7-432e-4802-b211-d3a193bab9a2
		summarizeBy: none
		sourceColumn: Number of Trees in Plot

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of Dead of Trees'
		dataType: string
		isHidden
		lineageTag: 9822fa3c-8f8c-4fc8-8261-c55662a5cd9d
		summarizeBy: none
		sourceColumn: Number of Dead of Trees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of Live Trees'
		dataType: string
		isHidden
		lineageTag: cd983206-4fc4-4733-84c7-8c6e116050ff
		summarizeBy: none
		sourceColumn: Number of Live Trees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Percent of trees that are dead'
		dataType: string
		isHidden
		lineageTag: fffe5dab-92f9-47ce-9c09-15cb4ecff0cf
		summarizeBy: none
		sourceColumn: Percent of trees that are dead

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Percent of trees that are live'
		dataType: string
		isHidden
		lineageTag: 51a70737-428c-4895-a04e-af3c1b0a92d7
		summarizeBy: none
		sourceColumn: Percent of trees that are live

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Percent of trees that could be assessed (e.g. No uncertainty)'
		dataType: string
		isHidden
		lineageTag: fcaa9440-59f2-41bd-a3a3-7b56edb99ed6
		summarizeBy: none
		sourceColumn: Percent of trees that could be assessed (e.g. No uncertainty)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of Trees with blister rust cankers'
		dataType: string
		isHidden
		lineageTag: 213f5658-c1cf-43e5-846f-1302e12ce8d5
		summarizeBy: none
		sourceColumn: Number of Trees with blister rust cankers

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Percent of live trees infected with blister rust (only trees confidently assessed)'
		dataType: string
		isHidden
		lineageTag: 2cec8795-1053-43e9-bc66-793198c19271
		summarizeBy: none
		sourceColumn: Percent of live trees infected with blister rust (only trees confidently assessed)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Percent of live trees that are healthy'
		dataType: string
		isHidden
		lineageTag: 47f13c60-dee5-47f0-a083-a4fac5b2a0bb
		summarizeBy: none
		sourceColumn: Percent of live trees that are healthy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Locator ID'
		dataType: string
		isHidden
		lineageTag: e982a723-cdda-473b-a5c9-71129b583f8d
		summarizeBy: none
		sourceColumn: Locator ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Invasive Yoho' = m
		mode: import
		queryGroup: 'Base Table Data'
		source =
				let
				    Source = Csv.Document(Web.Contents("https://mysait.sharepoint.com/sites/BSNCapstone200/Shared%20Documents/General/Capstone%20Datasets/alpine_blister_rust_yoho_data.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Park", type text}, {"Year", Int64.Type}, {"Plot", type text}, {"Species", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Province", type text}, {"Plot Area (m2)", Int64.Type}, {"Number of Trees in Plot", Int64.Type}, {"Number of Dead of Trees", Int64.Type}, {"Number of Live Trees", Int64.Type}, {"Percent of trees that are dead", Percentage.Type}, {"Percent of trees that are live", Percentage.Type}, {"Percent of trees that could be assessed (e.g. No uncertainty)", Percentage.Type}, {"Number of Trees with blister rust cankers", Int64.Type}, {"Percent of live trees infected with blister rust (only trees confidently assessed)", Percentage.Type}, {"Percent of live trees that are healthy", Percentage.Type}, {"Locator ID", Int64.Type}}),
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type", {{"Number of Dead of Trees", type text}}, "en-US"),{{"Park", Text.Trim, type text}, {"Number of Dead of Trees", Text.Trim, type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Trimmed Text",{{"Number of Dead of Trees", Int64.Type}}),
				    #"Cleaned Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type1", {{"Number of Dead of Trees", type text}}, "en-US"),{{"Number of Dead of Trees", Text.Clean, type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Cleaned Text",{{"Number of Dead of Trees", Int64.Type}}),
				    #"Trimmed Text1" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type2", {{"Year", type text}, {"Latitude", type text}, {"Longitude", type text}, {"Plot Area (m2)", type text}, {"Number of Trees in Plot", type text}, {"Number of Dead of Trees", type text}, {"Number of Live Trees", type text}, {"Percent of trees that are dead", type text}, {"Percent of trees that are live", type text}, {"Percent of trees that could be assessed (e.g. No uncertainty)", type text}, {"Number of Trees with blister rust cankers", type text}, {"Percent of live trees infected with blister rust (only trees confidently assessed)", type text}, {"Percent of live trees that are healthy", type text}, {"Locator ID", type text}}, "en-US"),{{"Park", Text.Trim, type text}, {"Year", Text.Trim, type text}, {"Plot", Text.Trim, type text}, {"Species", Text.Trim, type text}, {"Latitude", Text.Trim, type text}, {"Longitude", Text.Trim, type text}, {"Province", Text.Trim, type text}, {"Plot Area (m2)", Text.Trim, type text}, {"Number of Trees in Plot", Text.Trim, type text}, {"Number of Dead of Trees", Text.Trim, type text}, {"Number of Live Trees", Text.Trim, type text}, {"Percent of trees that are dead", Text.Trim, type text}, {"Percent of trees that are live", Text.Trim, type text}, {"Percent of trees that could be assessed (e.g. No uncertainty)", Text.Trim, type text}, {"Number of Trees with blister rust cankers", Text.Trim, type text}, {"Percent of live trees infected with blister rust (only trees confidently assessed)", Text.Trim, type text}, {"Percent of live trees that are healthy", Text.Trim, type text}, {"Locator ID", Text.Trim, type text}}),
				    #"Cleaned Text1" = Table.TransformColumns(#"Trimmed Text1",{{"Park", Text.Clean, type text}, {"Year", Text.Clean, type text}, {"Plot", Text.Clean, type text}, {"Species", Text.Clean, type text}, {"Latitude", Text.Clean, type text}, {"Longitude", Text.Clean, type text}, {"Province", Text.Clean, type text}, {"Plot Area (m2)", Text.Clean, type text}, {"Number of Trees in Plot", Text.Clean, type text}, {"Number of Dead of Trees", Text.Clean, type text}, {"Number of Live Trees", Text.Clean, type text}, {"Percent of trees that are dead", Text.Clean, type text}, {"Percent of trees that are live", Text.Clean, type text}, {"Percent of trees that could be assessed (e.g. No uncertainty)", Text.Clean, type text}, {"Number of Trees with blister rust cankers", Text.Clean, type text}, {"Percent of live trees infected with blister rust (only trees confidently assessed)", Text.Clean, type text}, {"Percent of live trees that are healthy", Text.Clean, type text}, {"Locator ID", Text.Clean, type text}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Cleaned Text1",{{"Park", type text}, {"Year", Int64.Type}, {"Plot", type text}, {"Species", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Province", type text}, {"Plot Area (m2)", Int64.Type}, {"Number of Trees in Plot", Int64.Type}, {"Number of Dead of Trees", Int64.Type}, {"Number of Live Trees", Int64.Type}, {"Percent of trees that are dead", type number}, {"Percent of trees that are live", type number}, {"Percent of trees that could be assessed (e.g. No uncertainty)", type number}, {"Number of Trees with blister rust cankers", Int64.Type}, {"Percent of live trees infected with blister rust (only trees confidently assessed)", type number}, {"Percent of live trees that are healthy", type number}, {"Locator ID", Int64.Type}}),
				    #"Demoted Headers" = Table.DemoteHeaders(#"Changed Type3"),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Demoted Headers",{{"Column1", type text}, {"Column2", type any}, {"Column3", type text}, {"Column4", type text}, {"Column5", type any}, {"Column6", type any}, {"Column7", type text}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}}),
				    #"Trimmed Text2" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type4", {{"Column2", type text}, {"Column5", type text}, {"Column6", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}}, "en-US"),{{"Column1", Text.Trim, type text}, {"Column2", Text.Trim, type text}, {"Column3", Text.Trim, type text}, {"Column4", Text.Trim, type text}, {"Column5", Text.Trim, type text}, {"Column6", Text.Trim, type text}, {"Column7", Text.Trim, type text}, {"Column8", Text.Trim, type text}, {"Column9", Text.Trim, type text}, {"Column10", Text.Trim, type text}, {"Column11", Text.Trim, type text}, {"Column12", Text.Trim, type text}, {"Column13", Text.Trim, type text}, {"Column14", Text.Trim, type text}, {"Column15", Text.Trim, type text}, {"Column16", Text.Trim, type text}, {"Column17", Text.Trim, type text}, {"Column18", Text.Trim, type text}}),
				    #"Cleaned Text2" = Table.TransformColumns(#"Trimmed Text2",{{"Column1", Text.Clean, type text}, {"Column2", Text.Clean, type text}, {"Column3", Text.Clean, type text}, {"Column4", Text.Clean, type text}, {"Column5", Text.Clean, type text}, {"Column6", Text.Clean, type text}, {"Column7", Text.Clean, type text}, {"Column8", Text.Clean, type text}, {"Column9", Text.Clean, type text}, {"Column10", Text.Clean, type text}, {"Column11", Text.Clean, type text}, {"Column12", Text.Clean, type text}, {"Column13", Text.Clean, type text}, {"Column14", Text.Clean, type text}, {"Column15", Text.Clean, type text}, {"Column16", Text.Clean, type text}, {"Column17", Text.Clean, type text}, {"Column18", Text.Clean, type text}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Cleaned Text2",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}}),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Changed Type5", [PromoteAllScalars=true])
				in
				    #"Promoted Headers1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

